name: Deploy React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker Image
        run: docker build -t mwangi34/react-app .
      - name: Publish Image to Docker Hub
        run: docker push mwangi34/react-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull mwangi34/react-app:latest
      - name: Delete old Container
        run: docker rm -f reactjs-app-container
      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name reactjs-app-container mwangi34/react-app:latest
