name: Deploy React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker Image
        run: docker build -t mwangi34/react-app:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push mwangi34/react-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Pull Docker Image
        run: docker pull mwangi34/react-app:latest

      - name: Stop and Remove Existing Container
        run: |
          docker stop reactjs-app-container || true
          docker rm reactjs-app-container || true

      - name: Run Docker Container
        run: docker run -d -p 80:80 --name reactjs-app-container mwangi34/react-app:latest
